### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by toprak** [mienaiyami/yomikiru#264]
### Type of installation

Portable (.zip)

### Steps to reproduce

```git clone https://github.com/mienaiyami/yomikiru
cd yomikiru
yarn
yarn make
cd out/Yomikiru-linux-x64/
./yomikiru
```

### ✔️ Expected Behavior

See UI properly

### ❌ Actual Behavior

only blank screen totally darkness, 2.17.8 works properly though

**Comment by mienaiyami** [comment]
- Can you show the output in the terminal where you ran this? 
- Are you running this on WSL or some linux distro?

**Comment by toprak** [comment]
@mienaiyami running on arch linux
there is not but this ```08:22:31.127 › Starting app...```

**Comment by mienaiyami** [comment]
I havent tested the app on arch linux, and unfortunately I dont know much about it. It might be an issue related to accessing files. Can you click `ctrl+shift+i` inside the blank app and check for errors in the popup window.

**Comment by toprak** [comment]
@mienaiyami here
```TypeError: window.electron.getCurrentWindow(...).setTitleBarOverlay is not a function
    at t.setSysBtnColor (index.js:2:2725277)
    at e (index.js:2:2646534)
    at index.js:2:2646623
    at index.js:2:2646727
    at mo (index.js:2:2166620)
    at Ns (index.js:2:2183645)
    at t.unstable_runWithPriority (index.js:2:2240611)
    at qc (index.js:2:2125819)
    at Ls (index.js:2:2180384)
    at As (index.js:2:2176495)
oo @ index.js:2
index.js:2 Uncaught TypeError: window.electron.getCurrentWindow(...).setTitleBarOverlay is not a function
    at t.setSysBtnColor (index.js:2:2725277)
    at e (index.js:2:2646534)
    at index.js:2:2646623
    at index.js:2:2646727
    at mo (index.js:2:2166620)
    at Ns (index.js:2:2183645)
    at t.unstable_runWithPriority (index.js:2:2240611)
    at qc (index.js:2:2125819)
    at Ls (index.js:2:2180384)
    at As (index.js:2:2176495)
```

**Comment by mienaiyami** [comment]
Can you pull and try make again now.
I would have use arch on VM to check this but unfortunately I cant for few days.

**Comment by toprak** [comment]
@mienaiyami done
